language: node_js
node_js:
- '0.10'
script: gulp build
deploy:
  provider: divshot
  api_key:
    secure: RIXC3U7+E8ieDbZ9ZIIoR7UioahCVq/1wJfwZDSlyEIBxNeZcfAZ+cx4OVXpIy7jq1SF8h09HLkScsPIXqP8JBE340UPeAxTtifDwNxj3PlQ0XaQR+szaf4hlGJX2pjEW1+Oui3Ds0gq+g6raKpcflUhdiKpQzuavoArJL/ZLQ0=
  skip_cleanup: true
  on:
    repo: MindKitchen/oven.mindkitchen.co
notifications:
  webhooks:
    urls:
      secure: NMP7zW5Kq8RVFz4pTNP8y5sNnYAcYapEpEroCqFT1MyIDxWv3yWfBX6/frU/4oZxYfkRIF3qKpJ0fttUFb+HmfP7J+LqVpvz+4AyD5OyuLhC6zSipp9WeXnnT+frrGvllNAzG3FM1rTduwMMABGBsvSgZsMO/90fFkFnMEpc7rA=
  slack:
    secure: DS7km6/5Kn3CKNpj7KTYMgJEk+N4Cubtdu2N7XZpRJvJV4BF1SMMQs10wCB6fjHcfggwdj94sDPCrwbzwJSFsI+E7CeI3EjjJt6RQDDGylP9rFhAmEHKNkvmPbi2obWqpCVKgn/nWUXkzS0cx/gQuNizkxGPS/8v6zFDb2i2gYc=
